/**
 * Vercel serverless function entry point for Expo Router API routes
 *
 * This function delegates all requests to the Expo server bundle.
 * The server bundle is generated by `expo export -p web` and contains
 * all API routes defined with the +api.ts suffix in the app directory.
 *
 * @see https://docs.expo.dev/router/web/api-routes/
 */

const { createRequestHandler } = require('expo-server/adapter/vercel');

module.exports = createRequestHandler({
  build: require('path').join(__dirname, '../dist/server'),
});
